export const fitnessChallenges = [
	"Do 20 push-ups",
	"Do 15 squats",
	"Do 10 burpees",
	"Hold a plank for 30 seconds",
	"Do 20 jumping jacks",
	"Run in place for 1 minute",
	"Stretch for 5 minutes",
	"Do 10 lunges per leg",
	"Try 1-minute wall sit",
	"Do 25 sit-ups",
	"Do 15 tricep dips on a chair",
	"Walk up and down stairs 5 times",
	"Do 10 push-ups on your knuckles",
	"Do 10 calf raises",
	"Hold a bridge pose for 20 seconds",
	"Do 15 high knees",
	"Do 10 side lunges",
	"Do 1-minute skipping (in place)",
	"Balance on one leg for 30 seconds",
	"Do 10 mountain climbers",
	"Do 15 glute bridges",
	"Try 10 wide push-ups",
	"Do 20 bicycle crunches",
	"Try 10 reverse crunches",
	"Hold a plank for 1 minute",
	"Do 15 jump squats",
	"Do 10 push-ups with feet elevated",
	"Walk briskly for 5 minutes",
	"Do 15 side planks (each side)",
	"Try 20 toe touches",
	"Do 15 donkey kicks (each leg)",
	"Do 15 side leg raises",
	"Try 10 handstand kick-ups (against wall)",
	"Do 15 Russian twists",
	"Try 20 step-ups on a chair",
	"Do 10 wide squats",
	"Do 20 arm circles",
	"Do 10 push-ups clapping in between",
	"Try 20-second headstand balance (wall)",
	"Do 10 burpees with jump",
	"Do 25 jumping jacks",
	"Do 15 plank shoulder taps",
	"Try 1-minute yoga sun salutation",
	"Do 10 frog jumps",
	"Hold child’s pose for 30 seconds",
	"Do 20 skater jumps",
	"Do 10 push-ups slowly",
	"Do 15 chair squats",
	"Do 20 heel touches",
	"Try 10 diamond push-ups"
];