export const lifestyleChallenges = [
	"Drink a full glass of water",
	"Clean your desk",
	"Organize one drawer",
	"Make your bed",
	"Write a to-do list",
	"Take a 5-minute walk",
	"Compliment someone",
	"Message a friend",
	"Water a plant",
	"Throw away 3 useless things",
	"Wash your hands for 30 seconds",
	"Eat a fruit",
	"Stretch for 2 minutes",
	"Take 3 deep breaths",
	"Write down a dream",
	"Plan tomorrow’s breakfast",
	"Fold your clothes",
	"Listen to a new song",
	"Take a picture of something nice",
	"Write one positive thought",
	"Check your calendar",
	"Brush your teeth",
	"Wash your face",
	"Organize your bag",
	"Put your phone away for 10 minutes",
	"Declutter one folder in your phone",
	"Unsubscribe from one spam email",
	"Delete 5 useless photos",
	"Close your eyes for 1 minute",
	"Say thank you to someone",
	"Smile in the mirror",
	"Set a timer for 10 minutes of focus",
	"Update one app",
	"Change your bedsheet",
	"Dust your room",
	"Light a candle or incense",
	"Eat one healthy snack",
	"Plan your weekend",
	"Clean your shoes",
	"Polish something in your room",
	"Wash one cup/plate",
	"Check your wallet",
	"Read your old notes",
	"Turn off unused lights",
	"Do 1 act of kindness",
	"Sit quietly for 2 minutes",
	"Stretch your arms overhead",
	"Massage your temples",
	"Drink warm water",
	"Say something nice about yourself"
];