export const codingChallenges = [
	"Write a function to reverse a string",
	"Write a function to check if a number is even",
	"Create an array of 5 objects and log their names",
	"Write a function to find the largest number in an array",
	"Create a JavaScript object for a car",
	"Write a loop that prints numbers 1–20",
	"Make a function that counts vowels in a word",
	"Write a program that sums all numbers in an array",
	"Create an array of fruits and sort them",
	"Make a function that checks if a word is a palindrome",
	"Write a function that doubles each number in an array",
	"Write a function that removes duplicates from an array",
	"Create a function that generates a random number",
	"Build a timer that counts from 1 to 10",
	"Make a function that capitalizes each word in a string",
	"Create a basic calculator object",
	"Write code that prints a multiplication table (1–10)",
	"Write a function to merge two arrays",
	"Write a function to find the factorial of a number",
	"Make a to-do list array and add 3 tasks",
	"Write code that finds the minimum number in an array",
	"Write a function to shuffle an array",
	"Write a function to count words in a sentence",
	"Make a function that converts Celsius to Fahrenheit",
	"Write a function that returns today’s date",
	"Create a function that reverses an array",
	"Make a function that finds the longest word in a string",
	"Create a program that simulates rolling a dice",
	"Write a program to print Fibonacci sequence up to 10",
	"Write a function that removes spaces from a string",
	"Make a function that finds prime numbers up to 50",
	"Write a function that counts how many times a letter appears",
	"Write a function that trims extra spaces in a string",
	"Create a loop that prints only odd numbers",
	"Write a function that checks if two arrays are equal",
	"Write code that flattens a 2D array",
	"Create a function that finds the median of numbers",
	"Write a function to sort numbers ascending",
	"Write a function to generate a random password",
	"Create a function that checks if a year is a leap year",
	"Write a program that simulates coin flips",
	"Create an object with methods add, subtract, multiply, divide",
	"Write a function that finds the most frequent element in an array",
	"Write code that converts a string to title case",
	"Create a function that removes vowels from a string",
	"Write a function that repeats a string 5 times",
	"Write a program that prints a pyramid of stars",
	"Create a countdown timer in JavaScript",
	"Write a function to swap two numbers"
];