export const creativityChallenges = [
	"Draw something using only circles",
	"Make a doodle of your hand",
	"Write a 4-line poem",
	"Take a creative photo of an object near you",
	"Invent a superhero name for yourself",
	"Create a new emoji idea",
	"Write a funny short story (under 100 words)",
	"Try to sketch with your eyes closed",
	"Write a haiku",
	"Make up a new word and define it",
	"Draw your favorite food",
	"Create a comic strip with 3 frames",
	"Write 3 jokes",
	"Imagine an alien and draw it",
	"Draw a self-portrait in 1 minute",
	"Make a paper airplane",
	"Build something using only paper",
	"Hum or whistle a random tune",
	"Write down a movie idea",
	"Design a new logo for a random product",
	"Write 3 riddles",
	"Pretend you’re a fashion designer—draw a new outfit",
	"Draw your dream house",
	"Make up a tongue twister",
	"Create a random monster",
	"Draw a flower with eyes",
	"Write a list of funny movie titles",
	"Pretend you’re an inventor—make up a gadget",
	"Create a silly dance move",
	"Draw a face on your hand",
	"Write a tiny story in 5 emojis",
	"Design a simple board game idea",
	"Pretend you’re a chef—create a new dish name",
	"Write a rap line",
	"Draw a random shape and turn it into an animal",
	"Create a new holiday name",
	"Invent a superhero weakness",
	"Write your name backwards",
	"Draw a dragon breathing something other than fire",
	"Imagine a talking object and describe it",
	"Design your dream phone wallpaper",
	"Draw with your non-dominant hand",
	"Make up 5 funny hashtags",
	"Create a 2-line scary story",
	"Draw a fruit with legs",
	"Invent a new game rule for tic-tac-toe",
	"Write a fake newspaper headline",
	"Design a new playing card",
	"Draw a pizza with unusual toppings",
	"Imagine your pet can talk—write what it says"
];