export const foodChallenges = [
	"Drink a glass of lemon water",
	"Make a fruit salad",
	"Try a new recipe today",
	"Eat one vegetable you don’t usually eat",
	"Cook an egg in a new style",
	"Make a smoothie with 2 fruits",
	"Try a sugar-free snack",
	"Cook something without oil",
	"Bake something simple",
	"Eat only homemade food today",
	"Cut vegetables in creative shapes",
	"Try making a sandwich differently",
	"Make a wrap with leftovers",
	"Drink 2 liters of water today",
	"Eat something green",
	"Try a new spice",
	"Cook pasta in a new style",
	"Prepare a colorful plate (3+ colors of food)",
	"Skip junk food today",
	"Try eating with chopsticks",
	"Make popcorn at home",
	"Make a smoothie bowl",
	"Eat slowly and mindfully",
	"Prepare breakfast for someone else",
	"Try cooking rice differently",
	"Eat a protein-rich food",
	"Make homemade lemonade",
	"Try a salad dressing from scratch",
	"Drink green tea or herbal tea",
	"Try making soup",
	"Make your own sandwich spread",
	"Try a food you’ve never eaten before",
	"Create a funny face with food",
	"Bake cookies or muffins",
	"Try eating only fruits for one meal",
	"Make a pancake with toppings",
	"Eat only water-rich foods today",
	"Try making hummus or dip",
	"Make a snack without sugar",
	"Prepare a plate for someone you love",
	"Try eating with your non-dominant hand",
	"Eat something crunchy",
	"Make a smoothie with vegetables",
	"Prepare oats in a new way",
	"Make a DIY pizza",
	"Make a dessert with 3 ingredients",
	"Cook something from another country",
	"Eat one probiotic food (yogurt, kefir)",
	"Make a drink with mint leaves",
	"Try to cook a meal under 15 minutes"
];