export const learningChallenges = [
	"Learn one new English word",
	"Learn one new word in Spanish",
	"Read 5 pages of a book",
	"Watch a 10-minute educational video",
	"Write a short poem",
	"Learn a new math trick",
	"Memorize a short quote",
	"Try a simple coding problem",
	"Learn the capital of 3 countries",
	"Practice multiplication tables for 5 min",
	"Draw a quick sketch",
	"Write a short story (5 sentences)",
	"Learn a fact about space",
	"Learn one fact about history",
	"Learn one fact about animals",
	"Learn one fact about technology",
	"Memorize a phone number",
	"Try to count backwards from 100",
	"Solve a riddle",
	"Do a Sudoku puzzle",
	"Do a crossword puzzle",
	"Write a journal entry",
	"Memorize a short poem",
	"Read an article on Wikipedia",
	"Practice handwriting for 5 min",
	"Try mental math (no calculator)",
	"Write 10 synonyms for ‘happy’",
	"Write 10 antonyms for ‘sad’",
	"Learn 5 capitals of Europe",
	"Learn 5 capitals of Asia",
	"Learn 5 programming terms",
	"Learn 3 science facts",
	"Draw a map of your country",
	"Memorize 3 phone numbers",
	"Try to recite the alphabet backwards",
	"Write down your goals for today",
	"Try a tongue twister 5 times",
	"List 10 animals in 1 minute",
	"List 10 fruits in 1 minute",
	"List 10 countries in 1 minute",
	"List 10 famous people in 1 minute",
	"Learn 3 new emojis and their meaning",
	"Learn one new proverb",
	"Write a motivational sentence",
	"Write down 3 things you are grateful for",
	"Try to draw with your non-dominant hand",
	"Memorize 5 state names",
	"Translate 5 words into another language",
	"Summarize your favorite movie in 3 lines"
];