export const mindfulnessChallenges = [
	"Close your eyes and take 5 deep breaths",
	"Write down 3 things you’re grateful for",
	"Say 3 positive affirmations out loud",
	"Meditate for 2 minutes",
	"Listen to calming music for 5 minutes",
	"Stretch slowly for 1 minute",
	"Notice 3 things around you you hadn’t noticed",
	"Write down one worry and throw it away",
	"Sit quietly for 3 minutes",
	"Smile at yourself in the mirror",
	"Write one kind thing about yourself",
	"Do a body scan meditation",
	"Name 5 things you can see around you",
	"Name 4 things you can touch",
	"Name 3 things you can hear",
	"Name 2 things you can smell",
	"Name 1 thing you can taste",
	"Write a kind message to your future self",
	"Practice 1 minute of mindful breathing",
	"Stretch your arms slowly overhead",
	"Do 5 slow shoulder rolls",
	"Take a mindful sip of water",
	"Eat one bite of food slowly, noticing the taste",
	"Sit outside and listen to nature",
	"Close your eyes and imagine your happy place",
	"Say thank you to yourself",
	"Write a positive note and stick it somewhere",
	"Spend 5 minutes without your phone",
	"Do a quick neck massage",
	"Gently rub your hands together and feel the warmth",
	"Take 10 slow steps focusing on each step",
	"Draw a heart and color it in",
	"Write one small goal for today",
	"Think of someone you love and send them good thoughts",
	"Stretch your back gently",
	"Breathe in deeply for 4 seconds, exhale for 4",
	"Do a 1-minute guided meditation (YouTube)",
	"Imagine yourself succeeding at something",
	"List 3 things that made you smile this week",
	"Write down one happy memory",
	"Say a positive thing about someone else",
	"Look at the clouds for 2 minutes",
	"Watch the sunrise or sunset",
	"Write down one thing you forgive yourself for",
	"Do a 1-minute laughter exercise",
	"Give yourself a hug",
	"Draw a simple mandala",
	"Visualize your favorite place",
	"Think of 5 things you like about yourself"
];