export const socialChallenges = [
	"Call a friend you haven’t spoken to in a while",
	"Send a thank-you message to someone",
	"Compliment a stranger",
	"Smile at 5 people today",
	"Hold the door open for someone",
	"Ask someone how their day was",
	"Write a kind comment online",
	"Share something positive on social media",
	"Help a family member with a task",
	"Introduce yourself to someone new",
	"Message someone you miss",
	"Write a thank-you note",
	"Say hello to a neighbor",
	"Offer to help carry something for someone",
	"Donate old clothes",
	"Teach someone a skill",
	"Listen to someone without interrupting",
	"Share your food with someone",
	"Give directions if someone asks",
	"Invite a friend to join an activity",
	"Play a game with someone",
	"Tell a friend one thing you appreciate about them",
	"Ask someone about their hobbies",
	"Give someone a genuine smile",
	"Offer to help with homework/work",
	"Encourage someone who looks sad",
	"Say ‘good morning’ to 3 people",
	"Check on a family member",
	"Send a motivational quote to someone",
	"Help clean a shared space",
	"Do a random act of kindness",
	"Share your umbrella if it rains",
	"Offer someone a seat",
	"Compliment someone’s work",
	"Write a short letter to your best friend",
	"Help a sibling with something",
	"Congratulate someone for their success",
	"Offer water to someone",
	"Thank your parents/guardians",
	"Recommend a good book/movie to someone",
	"Talk to someone new at school/work",
	"Say something kind online today",
	"Invite a friend for a walk",
	"Encourage someone trying something new",
	"Lend a book to a friend",
	"Give a friend a small handmade gift",
	"Cheer for someone in sports/game",
	"Offer help without being asked",
	"Say something nice to a teacher/mentor",
	"Share a good memory with a friend"
];